version: "3.9"

services:
  product-service:
    build: ./product-service
    ports:
      - "5001:5001"

  cart-service:
    build: ./cart-service
    ports:
      - "5002:5002"

  order-service:
    build: ./order-service
    ports:
      - "5003:5003"

  frontend:
    build: ./frontend
    ports:
      - "8081:80"
