name: CI/CD Pipeline

on:
  push:
    branches: [main]

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  IMAGE_REPO: saikishore1234/microservice  

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    env:
      FRONTEND_IMAGE: ${{ env.IMAGE_REPO }}-frontend
      CART_IMAGE: ${{ env.IMAGE_REPO }}-cart
      ORDER_IMAGE: ${{ env.IMAGE_REPO }}-order
      PRODUCT_IMAGE: ${{ env.IMAGE_REPO }}-product

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build and push frontend image
        run: |
          docker build -t $FRONTEND_IMAGE:latest ./frontend
          docker push $FRONTEND_IMAGE:latest

      - name: Build and push cart service image
        run: |
          docker build -t $CART_IMAGE:latest ./cart-service
          docker push $CART_IMAGE:latest

      - name: Build and push order service image
        run: |
          docker build -t $ORDER_IMAGE:latest ./order-service
          docker push $ORDER_IMAGE:latest

      - name: Build and push product service image
        run: |
          docker build -t $PRODUCT_IMAGE:latest ./product-service
          docker push $PRODUCT_IMAGE:latest
